# Generated by Django 4.2.7 on 2024-01-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbluser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('vender_id', models.CharField(max_length=10, null=True)),
                ('product_id', models.CharField(max_length=10, null=True)),
                ('status', models.BooleanField(default=0)),
            ],
        ),
    ]
