# Generated by Django 4.2.7 on 2024-01-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_email_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('on_delete', models.BooleanField(default=0)),
                ('on_spam', models.BooleanField(default=0)),
                ('frm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_email', to='sms_email_app.tbluser')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_email', to='sms_email_app.tbluser')),
            ],
        ),
    ]
