# Generated by Django 4.2.7 on 2024-01-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_email_app', '0002_tblemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblemail',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
