# Generated by Django 4.2.7 on 2024-01-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_email_app', '0003_tblemail_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblspam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spamword', models.CharField(max_length=50, null=True)),
                ('on_delete', models.BooleanField(default=0)),
            ],
        ),
    ]
