# Generated by Django 4.2.7 on 2024-01-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_email_app', '0005_tblspam_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblemail',
            name='secretkey',
            field=models.IntegerField(null=True),
        ),
    ]
